Repository NicolaLampis/hackathon_ci, pull requests merged in 2021-03, with the labels that each got.

#1 Dev: Boilerplate code and add Bug Report Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  assets/css/style.css
  index.html
Labels: Development

#3 Dev: Add in Bootstrap CDN links to boilerplate code
  index.html
Labels: Development

#6 Dev: Added the irish banner to the index and game page, added the sty…
  README.md
  assets/css/style.css
  assets/images/irish-banner.png
  assets/images/shamrock-background.png
  game.html
  index.html
Labels: Development, documentation

#7 Added q&a to script.js
  README.md
  assets/js/script.js
Labels: Development

#8 added two images to the folder
  README.md
  assets/css/style.css
  assets/images/gold-pot.png
  assets/images/leprechaun.png
  index.html
Labels: Development

#9 Doc: Update the README.md Content
  README.md
  assets/images/coolors-palette-sm.png
  index.html
  wireframes/paddy-day-quiz.jpg
Labels: documentation

#12 Dev: changed button value to Start
  index.html
Labels: Development

#13 Dev: added questions and answers to script.js to total 50
  assets/js/script.js
Labels: Development

#14 adding dataQuiz.js
  assets/js/dataQuiz.js
Labels: Development, invalid

#15 Doc: Create TESTING.md file with template placeholder content
  TESTING.md
  assets/css/style.css
Labels: documentation

#19 changed the styling of the headers and the jumbotron
  README.md
  assets/css/style.css
  assets/images/bg-shamrock.jpg
  assets/images/gold-coins.png
  assets/images/gold-pot.png
  assets/images/original-shamrock-background.jpg
  assets/images/shamrock-background.png
  game.html
  index.html
Labels: Development

#20 Dev: adding Bootstrap to html and CSS footer
  assets/css/style.css
  index.html
Labels: Development

#23 did some small changes in style.css and game.html, changed some paddi…
  assets/css/style.css
  game.html
Labels: Development

#25 added and styled footer
  assets/css/style.css
  game.html
  index.html
Labels: Development

#26 Dev: changed colors for correct and incorrect answers
  README.md
  assets/css/style.css
  index.html
Labels: Development

#27 Dev: aded user goals, site owner goals to the README
  README.md
Labels: Development

#29 Dev: Added information to README about Favicon
  README.md
Labels: Development

#28 font-size => btn
  assets/css/style.css
  assets/js/script.js
  game.html
  index.html
Labels: Development

#30 Fix: bug fix on smaller devices where horizontal scroll bar appeared.…
  assets/css/style.css
  index.html
Labels: bug

#31 adding max-width to "banner"
  assets/css/style.css
  assets/js/dataQuez.js
Labels: Development

#32 did some minor changes at the top of the README and some minor fixing…
  README.md
  assets/images/paddy-day-rme.jpg
  assets/images/paddy-day-rme.png
  assets/images/rme-paddy- day.png
  index.html
Labels: documentation

#36 Dev: Refactor & Beuatify HTML & CSS fils and update README.md
  404.html
  README.md
  assets/css/404.css
  assets/css/style.css
  assets/images/coolors-palette-sm.png
  assets/images/screenshots/404-error.png
  assets/images/screenshots/game-body.png
  assets/images/screenshots/index-body.png
  assets/images/screenshots/index-footer.png
  assets/images/screenshots/quiz-answer-buttons.png
  game.html
  index.html
  wireframes/am-i-responsive.png
Labels: Development, bug, documentation

#37 Doc: README.md typos and styling issues corrected
  README.md
  assets/images/screenshots/github-projects.png
Labels: documentation

#39 Doc: Add new Development Lifecycle section and fix lots of typos and broken links
  README.md
Labels: documentation

#41 Doc: Update README Version Control section
  README.md
Labels: documentation

#43 Moving validation screenshoot to test.md
  TESTING.md
  validation/game_html.png
  validation/index_html.png
  validation/style_css.png
Labels: documentation

#44 Doc: TESTING.md document final touches and fixing typos / broken links
  TESTING.md
  testing/game-unit-test-plan.pdf
Labels: documentation

#45 Add credits and acknowledgements to code and README
  README.md
  TESTING.md
  assets/css/404.css
Labels: Development, documentation
